name: Email Step

inputs:
  mailconnection:
    description: Specify connection via URL,like smtp+starttls://user:password@server:port
    required: true
  jobname:
    required: true
  jobowner:
    required: true
  ghrepo:
    required: true
  ghrunid:
    required: true

runs:
  using: composite
  steps:
    - name: Email
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{ inputs.mailconnection }}
        subject: "Failure Notification - ${{ inputs.jobname }}"
        body: |
          Notification: ${{ inputs.jobname }} failed in backend test,

          For details pls see "github.com/${{ inputs.ghrepo }}/actions/runs/${{ inputs.ghrunid }}"
        to: ${{ inputs.jobowner }}
        from: github_action@github.com
