name: Email Step

inputs:
  server:
    required: true
  port:
    required: true
  user:
    required: true
  pswd:
    required: true
  jobname:
    required: true
  jobowner:
    required: true
  ghrepo:
    required: true
  ghrunid:
    required: true

runs:
  using: composite
  steps:
    - name: Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ inputs.server }}
        server_port: ${{ inputs.port }}
        username: ${{ inputs.user }}
        password: ${{ inputs.pswd }}        
        subject: "Failure Notification - ${{ inputs.jobname }}"
        body: |
          Notification: ${{ inputs.jobname }} failed in backend test,

          For details pls see "github.com/${{ inputs.ghrepo }}/actions/runs/${{ inputs.ghrunid }}"
        to: ${{ inputs.jobowner }}
        from: github_action@github.com
