name: Email Step

inputs:
  jobname:
    required: true
  jobowner:
    required: true
  ghrepo:
    required: true
  ghrunid:
    required: true

runs:
  using: composite
  steps:
    - name: Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.MAIL_SERVER }}
        server_port: ${{ secrets.MAIL_SERVER_PORT }}
    		username: ${{ secrets.MAIL_USERNAME }}
    		password: ${{ secrets.MAIL_PASSWORD }}        
        subject: "Failure Notification - ${{ inputs.jobname }}"
        body: |
          Notification: ${{ inputs.jobname }} failed in backend test,

          For details pls see "github.com/${{ inputs.ghrepo }}/actions/runs/${{ inputs.ghrunid }}"
        to: ${{ inputs.jobowner }}
        from: github_action@github.com
